version: '3.8'
services:
  database:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - uno
  backend:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - database
      - redis
    networks:
      - uno

  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server "
    container_name: redis
    env_file:
      - .env
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - uno

networks:
  uno:
    driver: bridge
