version: '3.8'
services:
  database: 
    image: postgres:latest
    container_name: postgres-database
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - uno

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

networks:
  uno: 